export const LOCAL_STORAGE_KEY = 'zipCodes';

export const OPERATIONS = {
  ZIP_CODE_ALREADY_PRESENT: "ZIP_CODE_ALREADY_PRESENT",
  ZIP_CODE_NOT_FOUND: "ZIP_CODE_NOT_FOUND",
  SUCCESS: "OPERATION_SUCCESS"
};
